project:
  type: website

website:
  title: "Land Terrier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - land_terrier_instructions_user.qmd
      - technical_guide.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
