project:
  type: website

website:
  title: "Land Terrier"
  navbar:
    left:
      - href: index.qmd
        text: Installation
      - user_guide.qmd
      - technical_guide.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    fig-align: center

editor: visual
